{% set version = "0.9.0" %}

package:
  name: regionmask
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regionmask/regionmask-{{ version }}.tar.gz
  sha256: 8da1b6359756241867c4e967097810ef86b9dff4e06d11ca648fe1d607e9cf14

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm

  run:
    - python >=3.6
    - geopandas >=0.6
    - numpy >=1.17
    - packaging >=20.0
    - pooch >=1.0
    - rasterio >=1.0
    - setuptools >=40.4
    - shapely >=1.6
    - xarray >=0.15

test:
  imports:
    - regionmask
    - regionmask.core
    - regionmask.defined_regions
  requires:
    - pytest

about:
  home: https://github.com/regionmask/regionmask
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'plotting and creation of masks of spatial regions'
  doc_url: http://regionmask.readthedocs.io/
  dev_url: https://github.com/regionmask/regionmask

extra:
  recipe-maintainers:
    - mathause
