{% set version = "0.13.0" %}

package:
  name: regionmask
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/regionmask/regionmask-{{ version }}.tar.gz
  sha256: 56fd11986cd2f03bd3ac3ecb19399bff3e8cb79e151f7e33e18121735123abdf

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=42
    - setuptools-scm >=7

  run:
    - python >=3.9
    - geopandas >=0.10
    - numpy >=1.21
    - packaging >=21.3
    - pooch >=1.4
    - rasterio >=1.2
    - shapely >=1.8
    - xarray >=0.20

  run_constrained:
    - cartopy >=0.20
    - cf_xarray >=0.7
    - matplotlib-base >=3.5

test:
  imports:
    - regionmask
    - regionmask.core
    - regionmask.defined_regions
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/regionmask/regionmask
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'plotting and creation of masks of spatial regions'
  doc_url: http://regionmask.readthedocs.io/
  dev_url: https://github.com/regionmask/regionmask

extra:
  recipe-maintainers:
    - mathause
