{% set version = "0.11.0" %}

package:
  name: regionmask
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regionmask/regionmask-{{ version }}.tar.gz
  sha256: 1c4c8fd44d413b174ba47dce952a0b26a82dc6d0d3c9b5e2486aad46346d785f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm

  run:
    - python >=3.7
    - geopandas >=0.7
    - numpy >=1.17
    - packaging >=21.3
    - pooch >=1.2
    - rasterio >=1.1
    - setuptools >=40.4
    - shapely >=1.7
    - xarray >=0.15

  run_constrained:
    - cartopy >=0.17
    - matplotlib >=3.2

test:
  imports:
    - regionmask
    - regionmask.core
    - regionmask.defined_regions
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/regionmask/regionmask
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'plotting and creation of masks of spatial regions'
  doc_url: http://regionmask.readthedocs.io/
  dev_url: https://github.com/regionmask/regionmask

extra:
  recipe-maintainers:
    - mathause
