{% set version = "0.8.0" %}

package:
  name: regionmask
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regionmask/regionmask-{{ version }}.tar.gz
  sha256: b37d9960c94178e88f47a1ac486c705bd9e2c96971739c1234312bff33f7ba48

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - geopandas >=0.6
    - numpy >=1.17
    - pooch >=1.0
    - rasterio >=1.0
    - shapely >=1.6
    - xarray >=0.15

test:
  imports:
    - regionmask
    - regionmask.core
    - regionmask.defined_regions
  requires:
    - pytest

about:
  home: https://github.com/regionmask/regionmask
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'plotting and creation of masks of spatial regions'
  doc_url: http://regionmask.readthedocs.io/
  dev_url: https://github.com/regionmask/regionmask

extra:
  recipe-maintainers:
    - mathause
