{% set version = "0.5.0" %}

package:
  name: regionmask
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regionmask/regionmask-{{ version }}.tar.gz
  sha256: 30de02890433500eee48a5ff9666b131ac0c00516ac7de8ec4880792995bded5

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - matplotlib-base
    - shapely
    - six
    - cartopy
    - rasterio
    - geopandas
    - xarray
    - affine

test:
  imports:
    - regionmask
    - regionmask.core
    - regionmask.defined_regions
  requires:
    - pytest

about:
  home: https://github.com/mathause/regionmask
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'plotting and creation of masks of spatial regions'
  doc_url: http://regionmask.readthedocs.io/
  dev_url: https://github.com/mathause/regionmask

extra:
  recipe-maintainers:
    - mathause
