{% set version = "0.13.0" %}
{% set python_min = "3.10" %}

package:
  name: regionmask
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/regionmask/regionmask-{{ version }}.tar.gz
  sha256: 56fd11986cd2f03bd3ac3ecb19399bff3e8cb79e151f7e33e18121735123abdf

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=42
    - setuptools-scm >=7

  run:
    - python >={{ python_min }}
    - geopandas >=0.13
    - numpy >=1.24
    - packaging >=23.1
    - pooch >=1.7
    - rasterio >=1.3
    - shapely >=2.0
    - xarray >=2023.07

  run_constrained:
    - cartopy >=0.22
    - cf_xarray >=0.8
    - matplotlib-base >=3.7

test:
  imports:
    - regionmask
    - regionmask.core
    - regionmask.defined_regions
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/regionmask/regionmask
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'plotting and creation of masks of spatial regions'
  doc_url: http://regionmask.readthedocs.io/
  dev_url: https://github.com/regionmask/regionmask

extra:
  recipe-maintainers:
    - mathause
