{% set version = "0.6.2" %}

package:
  name: regionmask
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regionmask/regionmask-{{ version }}.tar.gz
  sha256: 360d3628a16a50a2f5ce7873160d87775c33c6a9bc80f90c354aef2c52b9566e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - numpy
    - matplotlib-base
    - shapely
    - six
    - cartopy
    - rasterio
    - geopandas
    - xarray
    - affine
    - pooch

test:
  imports:
    - regionmask
    - regionmask.core
    - regionmask.defined_regions
  requires:
    - pytest

about:
  home: https://github.com/mathause/regionmask
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'plotting and creation of masks of spatial regions'
  doc_url: http://regionmask.readthedocs.io/
  dev_url: https://github.com/mathause/regionmask

extra:
  recipe-maintainers:
    - mathause
