travis:
  secure:
    BINSTAR_TOKEN: lnIuQNdaQOHZCXvO+pm4m1AnIyfyA0A918C9f8268aJCU4RZ6fLOyx9MzMnCTdQkj1fH08pgrR1L/bvz+ZDkKxcta0ZQmVRIyxwjhjirzY7m/L5CXZQYVa8PWUKDdH/qP/DAOsSRkMnJPS+jnGokh0mXWsAiv+5/RbPrzc/EZKrk3BE4TMpHGFrZqOh3nCUUJMB022vjRf46H05Mh81354fgdzQ4HmagcAJHkJ20jqyU//k6Ijos8HfFDdtNZO3LVNVDpEsEGyWDOnQ3qP3nTFiPGs4Pb6/sJmy1y3yRjf39orYQGCdCzMxHEwKdkTkQJHceghcMFkDJqYpkUfrS1ZamTcuzproTWDci7d4kx4Z5OZszFD8huTy7he07/cwmeoKkOL61SuJ0eU5wm+ex0ug5bAaA175MMiNXKPHyNGnC0rh4yoKvrHuSpMC7SLO+wxH/c9Wj8a8X0wHOB35ZJhsqRmsfDs0NXdD+q5jVYujmgsk/oUoRVzcFos0LKgB++VZteogsFKnawdEWgo+SZ9LoxxTKo4MLZawlAtiY+ui932ruxdTLJGtwgnm1YQQSQQKcOBQaTZ/ICd0KnIoO5sjvviWJmd9k93Eyjz0XjWym5A1eFUvCSaGCGf+E0a682DpyJL9OTKBcBhue9ZzT0van3qFtGEHKTrSLUJCDGas=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
