travis:
  secure:
    BINSTAR_TOKEN: ku8RCNIFpVKCpR4zyCAUh8+Qzj1wXdXMmFobsmq0IDSIRDfEfZ9SyFZa6v9ltfWSVc26G4pBZIj9clFhVoTYqSrUO3R7/10zLegWrWqQdcpcRiFT0cTiaoZadNgVfzWgq1LQnpvDSu7BPrxTLhsY0C7vARjxS6cKkKKeq3cc3ab/moXnMyUEiNL9i1ra1byK0nT4izMQ1kGjT5jOPECzJnfny3BXJBF5ZbOlxqApeqAj0b/qaXIE1aMIfmHUxyG3Qj3EO3Tp2ycYvliQidc3lP3pXPc7fsOMgecSMApRyLygozyu4MW2fwIRCL3H4pWb+mMgW6HyiAOawbytqhpMUEMmDeDC1L2ek2Uj9kyJMKsWeghYBTFhADKDUlQkWD1vF0E9TQcZmHwmitMjO09O2YWyBKomZzhAGcbiUEYGcFrngHIslzguMhMOJ6JGUscCANnvjeWkUDLST1+5Xc/dQBNFYw8YO47H4VlMz/ACgyalumgbCQcaPv1erFVFQbK2M8tUTIqtTeBzmqz+8L01xAnw6QOTAxz8WSiixuA/Pc9Za502c98HR0fBvT40+7GoNNDOpR5G8nAkFyFVwpazlCYJVi7NhkC0IQ4tVKfsOdBSsTXo2M2uaRlzRsEMXO4g9R3DfIVa+TUrp45+AViJuxR4ki3+ABJ8TP3lBRXM4uQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
